version: 2

models:
    - name: dim_listings_cleansed
      description: Cleansed table wich contains Airbnb listings.
      columns:

        - name: listing_id
          description: Unique identifier for each listing.
          tests:
            - unique
            - not_null

        - name: host_id
          description: Unique identifier for each host.
          tests:
            - not_null
            - relationships:
                to: ref('dim_hosts_cleansed')
                field: host_id

        - name: room_type
          description: The type of room the listing offers.
          tests:
            - accepted_values:
                values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
        
        - name: minimum_nights
          tests:
            - positive_value